### ISSUE TITLE
When CF_HOME environment specified, buildpack tests failed.

### ISSUE THREAD

**Issue by kanekoh** [cloudfoundry/machete#28]
I'd like to execute buildpack tests using CF_HOME environment because that I'm using shared environment with other developers.

The problem is that cf.config refers with `ENV['HOME']` in 'lib/machete/cf/app_guid_finder.rb' file. 
CF_HOME environment changes the directory where .cf directory is placed.

**Comment by sclevine** [comment]
Hi @kanekoh,

We released a new version of machete to address this: https://github.com/cloudfoundry/machete/commit/5db02ec6d64e3cb43a533241e7b041791486bc60
https://github.com/cloudfoundry/machete/releases/tag/v0.0.70
